spring.application.name=volunteens

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/volunteens_db
spring.datasource.username=postgres
spring.datasource.password=root1234

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect (optional for newer versions)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false